<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Akay.To.Azure" Version="0.0.12" />
    <PackageVersion Include="Akay.To.Core" Version="0.0.17" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
    <!--<PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />-->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="NetArchTest.Rules" Version="1.3.2" />
  </ItemGroup>
  <ItemGroup>
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.20.0.135146" />
  </ItemGroup>
</Project>