<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Akay.Be.Infrastructure.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.AI\Akay.To.AI.csproj" />
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.Azure\Akay.To.Azure.csproj" />
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.Core\Akay.To.Core.csproj" />
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.EF.SqlServer\Akay.To.EF.SqlServer.csproj" />
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.Messaging.Rebus\Akay.To.Messaging.Rebus.csproj" />
    <ProjectReference Include="..\Akay.Be.Application\Akay.Be.Application.csproj" />
    <ProjectReference Include="..\Akay.Be.Domain\Akay.Be.Domain.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalAkayTo)' == 'true' And Exists('..\..\..\Akay.To\Akay.To.Messaging.Rebus\Akay.To.Messaging.Rebus.csproj')">
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.Messaging.Rebus\Akay.To.Messaging.Rebus.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalAkayTo)' == 'true' And Exists('..\..\..\Akay.To\Akay.To.Core\Akay.To.Core.csproj')">
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.Core\Akay.To.Core.csproj" />
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.Azure\Akay.To.Azure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="Persistence\Repositories\" />
    <Folder Include="Persistence\Seed\" />
  </ItemGroup>
</Project>
