<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalAkayTo)' == 'true' And Exists('..\..\..\Akay.To\Akay.To.Core\Akay.To.Core.csproj')">
    <ProjectReference Include="..\..\..\Akay.To\Akay.To.Core\Akay.To.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalAkayTo)' != 'true'">
    <PackageReference Include="Akay.To.Core" VersionOverride="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akay.Be.Domain\Akay.Be.Domain.csproj" />
  </ItemGroup>
</Project>
